export const GET_ERRORS = 'GET_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const FORGOT_PASSWORD_SENT = 'FORGOT_PASSWORD_SENT';
export const PASSWORD_RESET = 'PASSWORD_RESET';
